services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: movie_ticketing
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: movie_ticketing

volumes:
  postgres_volume: